[package]
name = "computer-vision-rs"
version = "0.1.0"
authors = ["Matthieu Pizenberg <matthieu.pizenberg@gmail.com>"]
edition = "2018"

[dependencies]

# PistonDevelopers/image. Encoding/decoding images in Rust.
image = "0.19"

# PNG decoding and encoding
png = "0.12"

# Reading numbers in [big/little]-endian.
byteorder = "1.2"

# The core APIs, including the Serialize and Deserialize traits.
serde = "1.0"

# Support for #[derive(Serialize, Deserialize)].
serde_derive = "1.0"

# Each data format lives in its own crate;
serde_json = "1.0"

# Linear algebra
nalgebra = "0.15"

# Random number generators
rand = "0.5"

# Useful numeric traits
num-traits = "0.2"

# Parsing files
nom = "4"

# More iterators
itertools = "0.7"


[dev-dependencies]

# Property based testing
quickcheck = "0.6"

# Approximate equalities
approx = "0.2"

# CSV
csv = "1"
